In [2]:
# Source: https://github.com/mGalarnyk/Python_Tutorials/blob/master/Sklearn/PCA/PCA_Data_Visualization_Iris_Dataset_Blog.ipynb
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA, TruncatedSVD
from sklearn.preprocessing import StandardScaler
%matplotlib inline

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

df = pd.read_csv(url)
display(df.head())
display(df.shape)

5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

(149, 5)

In [40]:
features = ['sepal length', 'sepal width', 'petal length', 'petal width']
x = df.loc[:, features].values
y = df.loc[:,['target']].values

#Standardize the value in X

x = StandardScaler().fit_transform(x)
pd.DataFrame(data = x, columns = features).head()

sepal length  sepal width  petal length  petal width
0     -0.900681     1.032057     -1.341272    -1.312977
1     -1.143017    -0.124958     -1.341272    -1.312977
2     -1.385353     0.337848     -1.398138    -1.312977
3     -1.506521     0.106445     -1.284407    -1.312977
4     -1.021849     1.263460     -1.341272    -1.312977

In [41]:
pca = PCA(n_components=4)
pca.fit(x)
principalComponents = pca.transform(x)
principalComponents.shape

(150, 4)

In [69]:
cov_matrix = np.cov(principalComponents.T)
display(cov_matrix)
var_list = np.diagonal(cov_matrix)
var_list

array([[ 2.93035378e+00, -8.67308987e-17,  2.70977974e-17,
        -1.19435597e-16],
       [-8.67308987e-17,  9.27403622e-01,  3.47742181e-17,
         9.26766926e-17],
       [ 2.70977974e-17,  3.47742181e-17,  1.48342226e-01,
        -3.46508820e-17],
       [-1.19435597e-16,  9.26766926e-17, -3.46508820e-17,
         2.07460140e-02]])

array([2.93035378, 0.92740362, 0.14834223, 0.02074601])

In [70]:
display(pca.explained_variance_)

array([2.93035378, 0.92740362, 0.14834223, 0.02074601])

The variance from the cov matrix is the same as taken from object pca. The covariance is also the same.

In [74]:
display(pca.get_covariance())
display(np.cov(x.T))

array([[ 1.00671141, -0.11010327,  0.87760486,  0.82344326],
       [-0.11010327,  1.00671141, -0.42333835, -0.358937  ],
       [ 0.87760486, -0.42333835,  1.00671141,  0.96921855],
       [ 0.82344326, -0.358937  ,  0.96921855,  1.00671141]])

array([[ 1.00671141, -0.11010327,  0.87760486,  0.82344326],
       [-0.11010327,  1.00671141, -0.42333835, -0.358937  ],
       [ 0.87760486, -0.42333835,  1.00671141,  0.96921855],
       [ 0.82344326, -0.358937  ,  0.96921855,  1.00671141]])

# Explained variance

In [10]:
display(pca.explained_variance_)
display(pca.explained_variance_ratio_)

# Take the cumulative of explained variance
np.cumsum(pca.explained_variance_ratio_)

array([2.93035378, 0.92740362, 0.14834223, 0.02074601])

array([0.72770452, 0.23030523, 0.03683832, 0.00515193])

array([0.72770452, 0.95800975, 0.99484807, 1.        ])

## Checking the components
They are orthogonal with unit length

In [28]:
#display(pca.components_)
for i in [1,2,3]:
    print("Dot product of column 1 with column {} close to zero: ".format(i+1),np.allclose(0.0, pca.components_[:,0].dot(pca.components_[:, i])))
    print("Norm 2 of each columns {}: ".format(i+1), np.allclose(1.0, np.sum(pca.components_[:,i]** 2)))
    print()

Dot product of column 1 with column 2 close to zero:  True
Norm 2 of each columns 2:  True

Dot product of column 1 with column 3 close to zero:  True
Norm 2 of each columns 3:  True

Dot product of column 1 with column 4 close to zero:  True
Norm 2 of each columns 4:  True



In [87]:
# it's the components idempotent? The inverse = transpose
np.allclose(np.identity(4), pca.components_.dot(pca.components_.T))

True

# Try to replicate the transform function

In [36]:
compare_against = principalComponents[:10,:]
compare_against

array([[-2.26454173,  0.5057039 , -0.12194335, -0.02307332],
       [-2.0864255 , -0.65540473, -0.22725083, -0.10320824],
       [-2.36795045, -0.31847731,  0.05147962, -0.02782523],
       [-2.30419716, -0.57536771,  0.09886044,  0.06631146],
       [-2.38877749,  0.6747674 ,  0.02142785,  0.03739729],
       [-2.07053681,  1.51854856,  0.03068426, -0.00439877],
       [-2.44571134,  0.07456268,  0.34219764,  0.03809657],
       [-2.23384186,  0.24761393, -0.08257446,  0.02550516],
       [-2.34195768, -1.09514636,  0.1535624 ,  0.02679383],
       [-2.18867576, -0.44862905, -0.24655952,  0.0399073 ]])

## Multiply by the transpose of the components_
It's likely that the components in W_T matrix on wikipedia

In [66]:
nam_test = x[:10,:].dot(pca.components_)
# display(nam_test)
np.allclose(nam_test, compare_against)

nam_test = x[:10,:].dot(pca.components_.T)
# display(nam_test)
np.allclose(nam_test, compare_against)

True

In [ ]:
# Check the covariance matrix of the pca

In [51]:
# Calculate the loading according to this
# https://stackoverflow.com/questions/21217710/factor-loadings-using-sklearn
components2 = pca.components_.T * np.sqrt(pca.explained_variance_)
display(principalComponents[:10,:].dot(components2.T))
display(x[:10])
#np.allclose(nam_test, principalComponents[:10,:])

array([[-1.80892194,  1.45986444, -2.25224067, -2.18876415],
       [-2.03369523,  0.33338879, -2.11356296, -2.1091165 ],
       [-2.2448811 ,  0.787949  , -2.36301354, -2.29811539],
       [-2.29669022,  0.53633432, -2.2913633 , -2.24810346],
       [-1.90149353,  1.68100932, -2.35766364, -2.26796403],
       [-1.31537563,  2.28974159, -2.02819164, -1.9012676 ],
       [-2.25671188,  1.20161164, -2.40901889, -2.28264946],
       [-1.88677374,  1.22052019, -2.21919509, -2.16935135],
       [-2.53052186,  0.09445714, -2.34108609, -2.30107526],
       [-2.05102781,  0.56454885, -2.19563517, -2.21059759]])

array([[-0.90068117,  1.03205722, -1.3412724 , -1.31297673],
       [-1.14301691, -0.1249576 , -1.3412724 , -1.31297673],
       [-1.38535265,  0.33784833, -1.39813811, -1.31297673],
       [-1.50652052,  0.10644536, -1.2844067 , -1.31297673],
       [-1.02184904,  1.26346019, -1.3412724 , -1.31297673],
       [-0.53717756,  1.95766909, -1.17067529, -1.05003079],
       [-1.50652052,  0.80065426, -1.3412724 , -1.18150376],
       [-1.02184904,  0.80065426, -1.2844067 , -1.31297673],
       [-1.74885626, -0.35636057, -1.3412724 , -1.31297673],
       [-1.14301691,  0.10644536, -1.2844067 , -1.4444497 ]])

# Follow wikipedia
https://en.wikipedia.org/wiki/Principal_component_analysis

In [54]:
# https://stackoverflow.com/questions/31523575/get-u-sigma-v-matrix-from-truncated-svd-in-scikit-lear
from scipy.sparse.linalg import svds
u, s, w = svds(x.T.dot(x), k=3)
eigen_vectors = u.dot(np.sqrt(np.diag(s)))
eigen_vectors

array([[  3.38977537,   4.37665169, -10.9152261 ],
       [ -1.13788899,  10.88003921,   5.50293763],
       [ -0.66238831,   0.2479719 , -12.14560409],
       [ -2.97974244,   0.76897103, -11.81873642]])

In [57]:
x_transformed = x.dot(w.T)
#np.corrcoef(x_transformed)
x_transformed.shape

(150, 3)

it is true that w.T is the matrix where each column is the loading?

In [80]:
for i in range(3):
    display(np.sum(w.T[:,i]** 2))

0.9999999999999778

1.0000000000000004

1.0000000000000004

Check the correlation matrix. Note that numpy wants each row to be a variable, so I have to transpose it.

In [59]:
display(np.corrcoef(x_transformed.T))
display(np.allclose(np.identity(x_transformed.shape[1]), np.corrcoef(x_transformed.T)))

array([[ 1.00000000e+00,  1.76983659e-16,  5.43959094e-16],
       [ 1.76983659e-16,  1.00000000e+00, -4.45484414e-16],
       [ 5.43959094e-16, -4.45484414e-16,  1.00000000e+00]])

True

In [64]:
# Check the covariance
display(np.cov(x_transformed.T))
np.var(x_transformed, axis=0)

array([[ 1.48342226e-01,  6.56447442e-17,  3.58639950e-16],
       [ 6.56447442e-17,  9.27403622e-01, -7.34390306e-16],
       [ 3.58639950e-16, -7.34390306e-16,  2.93035378e+00]])

array([0.14735328, 0.92122093, 2.91081808])

The covariance is actually in ascending order. Not sure if there is normally any order at all.